### ISSUE TITLE
0.4.0 syntax error on line 1 - $

### ISSUE THREAD

**Issue by ilovezfs** [elboza/dwarf-ng#5]
With 0.4.0, the Homebrew test block is failing. `git bisect` leads me to 4ec934daa6325f6523bae2a417534f00994b850b as the first bad commit.

The error is
```
iMac-TMP:dwarf-ng joe$ dwarf -c 'print $mac' hello
syntax error on line 1 - $
```

With 0.3.2 this prints
```
iMac-TMP:dwarf-ng joe$ dwarf -c 'print $mac' hello
hello opened
magic: 0xfeedfacf (-17958193)
cputype: 0x1000007 (16777223)
cpusubtype: 0x80000003 (-2147483645)
filetype: 0x2 (2)
ncmds: 0xf (15)
sizeofcmds: 0x4b0 (1200)
flags: 0x200085 (2097285)
reserved: 0x0 (0)
Bye.
```

`hello` is
```
#include <stdio.h>

int main(int argc, char *argv[]) {
  printf("hello world\n");
}
```
compiled.

**Comment by elboza** [comment]
with dwarf-0.4.0 the parser and all the basic commands has changed. Now 'print' is not part of dwarf's commands any more. Use 'pp' (print alias) instead.

**Comment by ilovezfs** [comment]
Thanks @elboza!
